### PR TITLE
Fix Unhandled Interrupted system call in PipeLoggerServer 

### LINKED ISSUE #8: Unhandled Interrupted system call in PipeLoggerServer
Hey,

When running msbuild with MSBuildPipeLogger on a GitHub Action linux, I got the following error:

```
 Unhandled exception. System.IO.IOException: Interrupted system call
   ---> System.Net.Sockets.SocketException (4): Interrupted system call
     at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
     --- End of inner exception stack trace ---
     at System.IO.Pipes.PipeStream.ReadCore(Span`1 buffer)
     at MsBuildPipeLogger.PipeBuffer.Buffer.FillFromStream(Stream stream, CancellationToken cancellationToken)
     at MsBuildPipeLogger.PipeBuffer.FillFromStream(Stream stream, CancellationToken cancellationToken)
     at MsBuildPipeLogger.PipeLoggerServer`1.<.ctor>b__12_0()
     at System.Threading.Thread.StartCallback()
```

Should we catch SocketException as well? (not sure if `(4): Interrupted system call` means that it's an end of stream or something more serious)

https://github.com/daveaglick/MsBuildPipeLogger/blob/68568d0ea98da37be3645304bdbaf1ee8442a0d2/src/MsBuildPipeLogger.Server/PipeLoggerServer.cs#L49-L71

### PR DESCRIPTION
**Pull request by xoofx**
Fixes #8

Replacing the narrow catch with a wider catch on `IOException` and it is fixing the issue.

### CODE REVIEW

**Comment by daveaglick** [comment]
Awesome! Glad you figured this out, because goodness knows it would have taken me _a lot_ longer :). I'll endeavor to get this merged and released tomorrow.

**Comment by xoofx** [comment]
Hey @daveaglick,

I have pushed 1 more commit after fighting with the server process not exiting correctly on Linux. It seems that the sockets can be in a completely dangling state that will block the threads to exit (at least the reader thread was entirely blocked).

This is a screenshot of the CI before/after I applied my fix. You can see that it was taking almost 20min, probably because the socket was blocking the threads. So configuring the reader and writer threads with `IsBackground = true` and then process was able to exit, it is now only taking 3min

image

I don't know why there is such a behavior on Linux and I don't think it is happening on Windows, so I believe that there is something wrong in .NET with sockets/pipe, but I can't workaround it without this fix.

I have a copy of the MsBuildPipeLogger pre-comppiled assemblies in my repo, so no rush.

**Comment by daveaglick** [comment]
Procrastination pays off again! :)

Also - awesome work, now I _know_ there's no way I would have been able to track this one down on my own, no matter how long I had.

**Comment by daveaglick** [comment]
Thanks! Merged and release going out now.

**Pull request merged**
